#config_version=5

hardware:
  platform: fast
  driverboards: fast

sound_system:
  master_volume: 1
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: 0.5
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.7
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 0.4

assets:
  sounds:
    default:
      load: preload
    music:
      track: music
    sfx:
      track: sfx
    voice:
      track: voice

sound_player:
  game_ended:
    default:
      action: stop
      priority: 400
  ball_started:
    default:
      action: stop
      priority: 400
    shooter_waiting:
      action: play
      loops: -1
  s_drain_inactive:
    shooter_waiting:
      action: stop
    default:
      action: play
      loops: -1
      track: music
  mode_spell_portal_started:
    default:
      action: play
      loops: -1
      track: music
    mode_theme:
      action: stop
  mode_carousel_stopped:
    mode_theme:
      action: play
      loops: -1
    default:
      action: stop

fast:
  debug: true
  ports: com7, com8
  watchdog: 1000
  rgb_buffer: 3

ball_holds:
  left_mode_saucer:
    balls_to_hold: 1
    hold_devices: bd_left_kicker
    enable_events: start_selection_mode
    disable_events: carousel_item_selected
    release_one_events: carousel_item_selected
  right_mode_saucer:
    balls_to_hold: 1
    hold_devices: bd_right_kicker
    enable_events: start_selection_mode
    disable_events: carousel_item_selected
    release_one_events: carousel_item_selected
  left_wizard_saucer:
    balls_to_hold: 1
    hold_devices: bd_left_kicker
    enable_events: mode_mini_wizard_lit_started
    disable_events: slide_mw_intro_4_removed
    release_one_events: slide_mw_intro_4_removed
  right_wizard_saucer:
    balls_to_hold: 1
    hold_devices: bd_right_kicker
    enable_events: mode_mini_wizard_lit_started
    disable_events: slide_mw_intro_4_removed
    release_one_events: slide_mw_intro_4_removed

player_vars:
  mode_value:
    initial_value: 1000000
  bonus_multiplier:
    initial_value: 1
  playfield_multiplier:
    initial_value: 1


modes:
  - base
  - spell_portal
  - spell_galaxy
  - spell_warp
  - mode_lit
  - carousel
  - mission1
  - mission2
  - mission3
  - mission4
  - bonus
  - combos
  - super_features
  - super_spinners
  - super_targets
  - super_slings
  - super_lanes
  - add_mode_value
  - playfield_multiplier
  - mini_wizard
  - mini_wizard_lit
#  - high_score

switches:
  s_left_flipper:
    number: 0-0
    tags: left_flipper
  s_right_flipper:
    number: 0-1
    tags: right_flipper
  s_action_button:
    number: 0-2
  s_start:
    number: 0-3
    tags: start
  s_right_kicker:
    number: 0-4
    platform_settings:
      debounce_open: 4
      debounce_close: 250
  s_right_spinner:
    number: 0-5
  s_right_captive_ball:
    number: 0-6
    platform_settings:
      debounce_open: 50
      debounce_close: 250
  s_left_captive_ball:
    number: 0-7
    platform_settings:
      debounce_open: 50
      debounce_close: 250
  s_drop_target5:
    number: 0-8
    platform_settings:
      debounce_open: 40
      debounce_close: 50
  s_drop_target4:
    number: 0-9
    platform_settings:
      debounce_open: 40
      debounce_close: 50
  s_drop_target3:
    number: 0-10
    platform_settings:
      debounce_open: 40
      debounce_close: 50
  s_drop_target2:
    number: 0-11
    platform_settings:
      debounce_open: 40
      debounce_close: 50
  s_drop_target1:
    number: 0-12
    platform_settings:
      debounce_open: 40
      debounce_close: 50
  s_left_spinner:
    number: 0-13
  s_left_kicker:
    number: 0-14
    platform_settings:
      debounce_open: 4
      debounce_close: 250
  s_left_inlane_far:
    number: 0-15
  s_right_sling:
    number: 0-16
  s_right_inlane:
    number: 0-17
  s_right_inlane_far:
    number: 0-18
  s_drain:
    number: 0-19
    platform_settings:
      debounce_open: 150
      debounce_close: 100
  s_left_sling:
    number: 0-20
  s_left_inlane:
    number: 0-21


coils:
    c_flipper_left_main:
        number: 0-0
        default_pulse_ms: 12
    c_flipper_left_hold:
        number: 0-1
        allow_enable: true
    c_flipper_right_main:
        number: 0-2
        default_pulse_ms: 12
    c_flipper_right_hold:
        number: 0-3
        allow_enable: true
    c_target_reset:
        number: 0-4
        default_pulse_ms: 40
    c_right_kicker_eject:
        number: 0-5
        default_pulse_ms: 30
    c_left_kicker_eject:
        number: 0-6
        default_pulse_ms: 30
    c_drain_eject:
        number: 0-7
        default_pulse_ms: 30

lights:
  l_portal_p:
    number: 0-0
    subtype: led
    type: grb
  l_portal_o:
    number: 0-1
    subtype: led
    type: grb
  l_portal_r:
    number: 0-2
    subtype: led
    type: grb
  l_portal_t:
    number: 0-3
    subtype: led
    type: grb
  l_right_kicker:
    number: 0-4
    subtype: led
    type: grb
  l_right_inlane:
    number: 0-5
    subtype: led
    type: grb
  l_portal_a:
    number: 0-6
    subtype: led
    type: grb
  l_portal_l:
    number: 0-7
    subtype: led
    type: grb
  l_right_dimension:
    number: 0-8
    subtype: led
    type: grb
  l_warp_p:
    number: 0-9
    subtype: led
    type: grb
  l_mission8_1:
    number: 0-10
    subtype: led
    type: grb
  l_mission8_2:
    number: 0-11
    subtype: led
    type: grb
  l_mission8_3:
    number: 0-12
    subtype: led
    type: grb
  l_mission4_1:
    number: 0-13
    subtype: led
    type: grb
  l_mission4_2:
    number: 0-14
    subtype: led
    type: grb
  l_mission4_3:
    number: 0-15
    subtype: led
    type: grb
  l_right_loop:
    number: 0-16
    subtype: led
    type: grb
  l_mission3_3:
    number: 0-17
    subtype: led
    type: grb
  l_mission3_2:
    number: 0-18
    subtype: led
    type: grb
  l_mission3_1:
    number: 0-19
    subtype: led
    type: grb
  l_mission7_3:
    number: 0-20
    subtype: led
    type: grb
  l_mission7_2:
    number: 0-21
    subtype: led
    type: grb
  l_mission7_1:
    number: 0-22
    subtype: led
    type: grb
  l_warp_r:
    number: 0-23
    subtype: led
    type: grb
  l_wizard_mode:
    number: 0-24
    subtype: led
    type: grb
  l_super_spinners:
    number: 0-25
    subtype: led
    type: grb
  l_super_targets:
    number: 0-26
    subtype: led
    type: grb
  l_super_lanes:
    number: 0-27
    subtype: led
    type: grb
  l_super_slings:
    number: 0-28
    subtype: led
    type: grb
  l_mini_wizard_mode:
    number: 0-29
    subtype: led
    type: grb
  l_left_loop:
    number: 1-0
    subtype: led
    type: grb
  l_mission1_3:
    number: 1-1
    subtype: led
    type: grb
  l_mission2_3:
    number: 1-2
    subtype: led
    type: grb
  l_mission2_2:
    number: 1-3
    subtype: led
    type: grb
  l_mission2_1:
    number: 1-4
    subtype: led
    type: grb
  l_mission6_3:
    number: 1-5
    subtype: led
    type: grb
  l_mission6_2:
    number: 1-6
    subtype: led
    type: grb
  l_mission6_1:
    number: 1-7
    subtype: led
    type: grb
  l_warp_a:
    number: 1-8
    subtype: led
    type: grb
  l_warp_w:
    number: 1-9
    subtype: led
    type: grb
  l_mission5_1:
    number: 1-10
    subtype: led
    type: grb
  l_mission5_2:
    number: 1-11
    subtype: led
    type: grb
  l_mission5_3:
    number: 1-12
    subtype: led
    type: grb
  l_mission1_1:
    number: 1-13
    subtype: led
    type: grb
  l_mission1_2:
    number: 1-14
    subtype: led
    type: grb
  l_left_kicker:
    number: 1-15
    subtype: led
    type: grb
  l_left_inlane:
    number: 1-16
    subtype: led
    type: grb
  l_left_dimension:
    number: 1-17
    subtype: led
    type: grb
  l_galaxy_y:
    number: 1-18
    subtype: led
    type: grb
  l_galaxy_x:
    number: 1-19
    subtype: led
    type: grb
  l_galaxy_a_2:
    number: 1-20
    subtype: led
    type: grb
  l_galaxy_l:
    number: 1-21
    subtype: led
    type: grb
  l_galaxy_a:
    number: 1-22
    subtype: led
    type: grb
  l_galaxy_g:
    number: 1-23
    subtype: led
    type: grb

#----- GI ---------

  l_gi_1:
    number: 2-0
    subtype: led
    type: rgb
  l_gi_2:
    number: 2-1
    subtype: led
    type: rgb
  l_gi_3:
    number: 2-2
    subtype: led
    type: rgb
  l_gi_4:
    number: 2-3
    subtype: led
    type: rgb
  l_gi_5:
    number: 2-4
    subtype: led
    type: rgb
  l_gi_6:
    number: 2-5
    subtype: led
    type: rgb
  l_gi_7:
    number: 2-6
    subtype: led
    type: rgb
  l_gi_8:
    number: 2-7
    subtype: led
    type: rgb
  l_gi_9:
    number: 2-8
    subtype: led
    type: rgb
  l_gi_10:
    number: 2-9
    subtype: led
    type: rgb
  l_gi_11:
    number: 2-10
    subtype: led
    type: rgb
  l_gi_12:
    number: 2-11
    subtype: led
    type: rgb
  l_gi_13:
    number: 2-12
    subtype: led
    type: rgb
  l_gi_14:
    number: 2-13
    subtype: led
    type: rgb
  l_left_shoot_again:
    number: 2-14
    subtype: led
    type: rgb
  l_right_shoot_again:
    number: 2-15
    subtype: led
    type: rgb
  l_gi_15:
    number: 2-16
    subtype: led
    type: rgb
  l_gi_16:
    number: 2-17
    subtype: led
    type: rgb
  l_gi_17:
    number: 2-18
    subtype: led
    type: rgb

#----- Drop target lights ------

  l_drop_target1:
    number: 3-0
    subtype: led
    type: rgb
  l_drop_target2:
    number: 3-1
    subtype: led
    type: rgb
  l_drop_target3:
    number: 3-2
    subtype: led
    type: rgb
  l_drop_target4:
    number: 3-3
    subtype: led
    type: rgb
  l_drop_target5:
    number: 3-4
    subtype: led
    type: rgb
#-----------------------

  l_rgb_right_kicker:
    number: 3-5
    subtype: led
    type: grb
  l_rgb_right_spinner:
    number: 3-6
    subtype: led
    type: grb
  l_rgb_left_spinner:
    number: 3-7
    subtype: led
    type: grb
  l_rgb_left_kicker:
    number: 3-8
    subtype: led
    type: grb



playfields:
    playfield:
        tags: default
        default_source_device: bd_drain

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: normal_flippers_enable, ball_started
    disable_events: weak_flipper_enable, ball_will_end
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: normal_flippers_enable, ball_started
    disable_events: weak_flipper_enable, ball_will_end

displays:
    window1:
        width: 1366
        height: 768

window:
  width: 1920 #1366
  height: 1080
#  fullscreen: true
  source_display: window1

mpf:
  default_light_hw_update_hz: 30

bcp:
  connections:
    local_display:
      host: localhost
      port: 5050
      type: mpf.core.bcp.bcp_socket_client.BCPClientSocket
      exit_on_close: true

keyboard:
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  s:
    switch: s_start
  '\':
    switch: s_action_button
  b:
    switch: s_drain

ball_devices:
  bd_drain:
    ball_switches: s_drain
    eject_coil: c_drain_eject
    tags: drain, home, trough
    eject_timeouts: 1s
    player_controlled_eject_event: s_action_button_active
  bd_left_kicker:
    ball_switches: s_left_kicker
    eject_coil: c_left_kicker_eject
    eject_timeouts: 1s
  bd_right_kicker:
    ball_switches: s_right_kicker
    eject_coil: c_right_kicker_eject
    eject_timeouts: 1s

drop_targets:
  far_left:
    switch: s_drop_target1
  left:
    switch: s_drop_target2
  middle:
    switch: s_drop_target3
  right:
    switch: s_drop_target4
  far_right:
    switch: s_drop_target5
drop_target_banks:
  main:
    drop_targets: far_left, left, middle, right, far_right
    reset_coils: c_target_reset
    reset_on_complete: 650ms
    reset_events:
      - ball_started
      - carousel_mission1_selected
      - mission1_phase4_start
      - mission1_phase3_start
      - mode_base_started
      - mode_mission3_started
      - mission3_phase2_start
      - light_drop_target1_path
      - light_drop_target2_path
      - light_drop_target3_path
      - light_drop_target4_path
      - light_drop_target5_path
      - final_shot_lit
