#config_version=5

mode:
  start_events: start_selection_mode
  stop_events: carousel_item_selected
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 90000

mode_settings:
  selectable_items:
    - mission1{not device.achievements.mission1.state=='completed'}
    - mission2{not device.achievements.mission2.state=='completed'}
    - mission3{not device.achievements.mission3.state=='completed'}
    - mission4{not device.achievements.mission4.state=='completed'}
    - endofcode{current_player.modes_completed == 4}
  select_item_events: s_action_button_inactive
  next_item_events: s_right_flipper_inactive
  previous_item_events: s_left_flipper_inactive

variable_player:
  carousel_mission1_selected:
    modes_started: 1
    selected_mission:
      action: set
      string: 'mission1'
  carousel_mission2_selected:
    modes_started: 1
    selected_mission:
      action: set
      string: 'mission2'
  carousel_mission3_selected:
    modes_started: 1
    selected_mission:
      action: set
      string: 'mission3'
  carousel_mission4_selected:
    modes_started: 1
    selected_mission:
      action: set
      string: 'mission4'

slide_player:
  carousel_mission1_highlighted: select_mission1
  carousel_mission2_highlighted: select_mission2
  carousel_mission3_highlighted: select_mission3
  carousel_mission4_highlighted: select_mission4
  carousel_endofcode_highlighted: select_endofcode

slides:
  select_mission1:
    widgets:
    - type: text
      text: MISSION 1
      font_name: space_font
      font_size: 100
      color: black
    - type: text
      text: SELECT LANDING SITE
      font_size: 40
      color: black
      font_name: space_font
      y: 80%
      animations:
        show_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            repeat: true
    - type: image
      image: mission1_select_bg
  select_mission2:
    - type: text
      text: MISSION 2
      font_name: space_font
      font_size: 100
      color: black
    - type: text
      text: SELECT LANDING SITE
      font_size: 40
      color: black
      font_name: space_font
      y: 80%
      animations:
        show_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            repeat: true
    - type: image
      image: mission2_select_bg
  select_mission3:
    - type: text
      text: MISSION 3
      font_size: 100
      font_name: space_font
    - type: text
      text: SELECT LANDING SITE
      font_size: 40
      y: 80%
      font_name: space_font
      animations:
        show_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            repeat: true
    - type: image
      image: mission3_select_bg
      scale: 2.2
  select_mission4:
    - type: text
      text: MISSION 4
      font_size: 100
      font_name: space_font
    - type: text
      text: SELECT LANDING SITE
      font_size: 40
      y: 80%
      font_name: space_font
      animations:
        show_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            repeat: true
    - type: image
      image: mission4_select_bg
    #  scale: 2.2
  select_endofcode:
    - type: text
      text: CONGRATS YOU MADE IT
      font_size: 50
      font_name: space_font
    - type: text
      text: TO THE END OF THE CODE!
      font_size: 50
      y: 25%
      font_name: space_font
    - type: text
      text: ACTION BUTTON TO CONTINUE
      font_size: 40
      y: 80%
      font_name: space_font
      animations:
        show_slide:
          - property: opacity
            value: 0
          - property: opacity
            value: 1
            repeat: true

    #  scale: 2.2
